[project]
name = "yaunet"
description = "A simple, module U-Net implementation in PyTorch."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "torch>=2.13.0",
    "einops>=0.8.2",
]
dynamic = ["version"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "yaunet.__version__"}

[tool.basedpyright]
typeCheckingMode = "standard"

[tool.ruff]
target-version = "py310"
line-length = 88
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.6",
]
